### PR TITLE
Catkin fix v2 v2.6 2 rplidar

### PR DESCRIPTION
**Pull request by gauthamm**
Added new versions of octomap, ompl and patch for boost to work with ompl

### CODE REVIEW

**Comment by jvgomez** [comment]
Although ompl and octomap recipes are temporary, I would merge them because we need them. In the future it will only change that instead of fetching a commit they will fetch an specific release.

@dominiquehunziker consider merging.

**Comment by dominiquehunziker** [comment]
what do you want to merge here; this is from one development branch into another. IMO both should be deprecated in favour of master.

**Comment by jvgomez** [comment]
We think the boost fix should be merged, even if it is another devel branch some people is using it as their master basically. The other recipes are optional (nor hamrful though) and if we can have just 1 branch why to have 2?

In any case, I agree we should favour the master, but this depends on a non-merged branch.

**Comment by jvgomez** [comment]
@jpardeiro consider merging this PR, we can converge on having a common meta-ros. If you are OK merging this, do not do it, we are testing a better patch for boost.

**Comment by gauthamm** [comment]
Since there is a secure branch which does the exact same as this branch, we will be closing this PR and deleting the branch.

**Pull request closed without merging**
